'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '../../lib/api';
import {useState as useStateAlias} from 'react';

type Counts={customers:number;agents:number;teachers:number;partners:number;products:number;orders:number;requests:number;messages:number};
type Partner={id:string;businessName:string;phone:string;location:string;status:string;_count:{products:number;orders:number}};
type User={id:string;email:string;phone:string|null;role:string;createdAt:string};
type Product={id:string;name:string;category:string;priceRwf:number|null;stock:number;status:string;partner:{businessName:string;status:string}};
type Order={id:string;customer:{email:string;phone:string|null};partner:{businessName:string};status:string;createdAt:string;items:Array<{quantity:number;product:{name:string}}>};
type Agent={id:string;displayName:string;phone:string;location:string;status:string;verificationStatus:string};
type Teacher={id:string;displayName:string;phone:string;location:string;status:string;verificationStatus:string};

export default function AdminPage(){
 const [counts,setCounts]=useState<Counts|null>(null);const [partners,setPartners]=useState<Partner[]>([]);const [products,setProducts]=useState<Product[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [users,setUsers]=useState<User[]>([]);const [agents,setAgents]=useState<Agent[]>([]);const [teachers,setTeachers]=useState<Teacher[]>([]);const [message,setMessage]=useState('');
 async function load(){const token=localStorage.getItem('lumia_token');if(!token){setMessage('Login as admin is required.');return;}try{const h={Authorization:'Bearer '+token};const [o,p,pr,ord,u,a,t]=await Promise.all([api<{counts:Counts}>('/api/v1/admin/overview',{headers:h}),api<{partners:Partner[]}>('/api/v1/admin/partners',{headers:h}),api<{products:Product[]}>('/api/v1/admin/products',{headers:h}),api<{orders:Order[]}>('/api/v1/admin/orders',{headers:h}),api<{users:User[]}>('/api/v1/admin/users',{headers:h}),api<{agents:Agent[]}>('/api/v1/admin/agents',{headers:h}),api<{teachers:Teacher[]}>('/api/v1/admin/teachers',{headers:h})]);setCounts(o.counts);setPartners(p.partners);setProducts(pr.products);setOrders(ord.orders);setUsers(u.users);setAgents(a.agents as Agent[]);setTeachers(t.teachers as Teacher[]);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load admin data.')}}
 useEffect(()=>{void load()},[]);

 async function importCatalog(){
   const token=localStorage.getItem('lumia_token');
   if(!token){setMessage('Login as admin is required.');return;}
   setMessage('');
   try{
     const partner=partners.find(p=>p.businessName==='LUMIA Verified Marketplace Sources');
     if(!partner){setMessage('LUMIA catalog partner not found.');return;}
     const products=productsForImport;
     const r=await api<{imported:number}>('/api/v1/marketplace/import',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({partnerId:partner.id,products})});
     setMessage('Imported '+r.imported+' products.');
     await load();
   }catch(e){setMessage(e instanceof Error?e.message:'Import failed.');}
 }
 async function status(id:string,status:'APPROVED'|'REJECTED'|'SUSPENDED'){const token=localStorage.getItem('lumia_token');if(!token)return;try{await api('/api/v1/admin/partners/'+id+'/status',{method:'PATCH',headers:{Authorization:'Bearer '+token},body:JSON.stringify({status})});await load();}catch(e){setMessage(e instanceof Error?e.message:'Update failed.')}}
 async function review(kind:'agents'|'teachers',id:string,verificationStatus:'VERIFIED'|'REJECTED'){const token=localStorage.getItem('lumia_token');if(!token)return;try{await api('/api/v1/admin/'+kind+'/'+id+'/status',{method:'PATCH',headers:{Authorization:'Bearer '+token},body:JSON.stringify({verificationStatus,status:verificationStatus==='VERIFIED'?'ACTIVE':'REJECTED'})});await load()}catch(e){setMessage(e instanceof Error?e.message:'Review failed.')}}
 return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div><div className="text-xs tracking-[.2em] text-slate-500">LUMIA</div><h1 className="mt-1 text-xl font-semibold">Admin Portal</h1></div><Link href="/dashboard" className="rounded-xl border border-white/10 px-3 py-2 text-sm">Customer dashboard</Link></div></header><div className="mx-auto max-w-7xl px-5 py-7"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{counts&&Object.entries(counts).map(([key,value])=><div key={key} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="text-xs uppercase tracking-wider text-slate-500">{key}</div><div className="mt-2 text-3xl font-semibold">{value}</div></div>)}</div>{message&&<div className="mt-5 rounded-xl bg-red-500/10 p-4 text-sm text-red-300">{message}</div>}<section className="mt-7 rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Partner applications</h2><p className="mt-1 text-sm text-slate-500">Approve real businesses before they can publish products.</p></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 px-3 py-2 text-sm">Refresh</button></div><div className="mt-5 space-y-3">{partners.length===0?<div className="rounded-2xl bg-white/[.03] p-5 text-sm text-slate-500">No partner applications.</div>:partners.map(p=><div key={p.id} className="rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="font-semibold">{p.businessName}</div><div className="mt-1 text-sm text-slate-500">{p.phone} · {p.location}</div><div className="mt-2 text-xs text-slate-400">Status: {p.status} · Products: {p._count.products} · Orders: {p._count.orders}</div></div><div className="flex gap-2">{p.status!=='APPROVED'&&<button onClick={()=>void status(p.id,'APPROVED')} className="rounded-xl bg-white px-3 py-2 text-xs font-semibold text-slate-950">Approve</button>}{p.status!=='REJECTED'&&<button onClick={()=>void status(p.id,'REJECTED')} className="rounded-xl border border-white/10 px-3 py-2 text-xs">Reject</button>}{p.status==='APPROVED'&&<button onClick={()=>void status(p.id,'SUSPENDED')} className="rounded-xl border border-white/10 px-3 py-2 text-xs">Suspend</button>}</div></div></div>)}</div></section><section className="mt-7 grid gap-6 lg:grid-cols-2">
<section className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><h2 className="font-semibold">Users & access</h2><div className="mt-4 max-h-80 space-y-2 overflow-auto">{users.map(u=><div key={u.id} className="rounded-xl border border-white/10 p-3 text-sm"><div>{u.email}</div><div className="mt-1 text-xs text-slate-500">{u.phone||'No phone'} · {u.role}</div></div>)}</div></section>
<section className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><h2 className="font-semibold">Products</h2><div className="mt-4 max-h-80 space-y-2 overflow-auto">{products.map(p=><div key={p.id} className="rounded-xl border border-white/10 p-3 text-sm"><div>{p.name}</div><div className="mt-1 text-xs text-slate-500">{p.category} · {p.stock} stock · {p.status} · {p.partner.businessName}</div></div>)}</div></section>
<section className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><h2 className="font-semibold">Orders</h2><div className="mt-4 max-h-80 space-y-2 overflow-auto">{orders.map(o=><div key={o.id} className="rounded-xl border border-white/10 p-3 text-sm"><div>{o.partner.businessName} · {o.status}</div><div className="mt-1 text-xs text-slate-500">{o.customer.email} · {o.items.map(i=>i.quantity+' × '+i.product.name).join(', ')}</div></div>)}</div></section>
<section className="rounded-3xl border border-white/10 bg-white/[.04] p-5"><h2 className="font-semibold">Providers & teachers</h2><div className="mt-4 space-y-2">{agents.map(a=><div key={a.id} className="rounded-xl border border-white/10 p-3 text-sm"><div>{a.displayName} · {a.status}/{a.verificationStatus}</div><div className="text-xs text-slate-500">{a.phone} · {a.location}</div></div>)}{teachers.map(t=><div key={t.id} className="rounded-xl border border-white/10 p-3 text-sm"><div>{t.displayName} · {t.status}/{t.verificationStatus}</div><div className="text-xs text-slate-500">{t.phone} · {t.location}</div></div>)}</div></section>
</section><section className="mt-7 rounded-3xl border border-white/10 bg-white/[.04] p-5"><h2 className="font-semibold">Provider & teacher approvals</h2><div className="mt-4 grid gap-3 lg:grid-cols-2">{[...agents.map(a=>({kind:'agents' as const,id:a.id,name:a.displayName,meta:a.phone+' · '+a.location,verification:a.verificationStatus})),...teachers.map(t=>({kind:'teachers' as const,id:t.id,name:t.displayName,meta:t.phone+' · '+t.location,verification:t.verificationStatus}))].map(item=><div key={item.kind+item.id} className="rounded-2xl border border-white/10 p-4"><div className="font-medium">{item.name}</div><div className="mt-1 text-xs text-slate-500">{item.meta}</div><div className="mt-1 text-xs text-slate-400">{item.kind} · {item.verification}</div><div className="mt-3 flex gap-2"><button onClick={()=>void review(item.kind,item.id,'VERIFIED')} className="rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-950">Approve</button><button onClick={()=>void review(item.kind,item.id,'REJECTED')} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Reject</button></div></div>)}</div></section></div></main>;
}
