'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '../../lib/api';

type Counts={customers:number;agents:number;teachers:number;partners:number;products:number;orders:number;requests:number;messages:number};
type Partner={id:string;businessName:string;phone:string;location:string;status:string;_count:{products:number;orders:number}};

export default function AdminPage(){
 const [counts,setCounts]=useState<Counts|null>(null);const [partners,setPartners]=useState<Partner[]>([]);const [message,setMessage]=useState('');
 async function load(){const token=localStorage.getItem('lumia_token');if(!token){setMessage('Login as admin is required.');return;}try{const h={Authorization:'Bearer '+token};const [o,p]=await Promise.all([api<{counts:Counts}>('/api/v1/admin/overview',{headers:h}),api<{partners:Partner[]}>('/api/v1/admin/partners',{headers:h})]);setCounts(o.counts);setPartners(p.partners);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load admin data.')}}
 useEffect(()=>{void load()},[]);
 async function status(id:string,status:'APPROVED'|'REJECTED'|'SUSPENDED'){const token=localStorage.getItem('lumia_token');if(!token)return;try{await api('/api/v1/admin/partners/'+id+'/status',{method:'PATCH',headers:{Authorization:'Bearer '+token},body:JSON.stringify({status})});await load();}catch(e){setMessage(e instanceof Error?e.message:'Update failed.')}}
 return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-white/10"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div><div className="text-xs tracking-[.2em] text-slate-500">LUMIA</div><h1 className="mt-1 text-xl font-semibold">Admin Portal</h1></div><Link href="/dashboard" className="rounded-xl border border-white/10 px-3 py-2 text-sm">Customer dashboard</Link></div></header><div className="mx-auto max-w-7xl px-5 py-7"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{counts&&Object.entries(counts).map(([key,value])=><div key={key} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="text-xs uppercase tracking-wider text-slate-500">{key}</div><div className="mt-2 text-3xl font-semibold">{value}</div></div>)}</div>{message&&<div className="mt-5 rounded-xl bg-red-500/10 p-4 text-sm text-red-300">{message}</div>}<section className="mt-7 rounded-3xl border border-white/10 bg-white/[.04] p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Partner applications</h2><p className="mt-1 text-sm text-slate-500">Approve real businesses before they can publish products.</p></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 px-3 py-2 text-sm">Refresh</button></div><div className="mt-5 space-y-3">{partners.length===0?<div className="rounded-2xl bg-white/[.03] p-5 text-sm text-slate-500">No partner applications.</div>:partners.map(p=><div key={p.id} className="rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="font-semibold">{p.businessName}</div><div className="mt-1 text-sm text-slate-500">{p.phone} · {p.location}</div><div className="mt-2 text-xs text-slate-400">Status: {p.status} · Products: {p._count.products} · Orders: {p._count.orders}</div></div><div className="flex gap-2">{p.status!=='APPROVED'&&<button onClick={()=>void status(p.id,'APPROVED')} className="rounded-xl bg-white px-3 py-2 text-xs font-semibold text-slate-950">Approve</button>}{p.status!=='REJECTED'&&<button onClick={()=>void status(p.id,'REJECTED')} className="rounded-xl border border-white/10 px-3 py-2 text-xs">Reject</button>}{p.status==='APPROVED'&&<button onClick={()=>void status(p.id,'SUSPENDED')} className="rounded-xl border border-white/10 px-3 py-2 text-xs">Suspend</button>}</div></div></div>)}</div></section></div></main>;
}
