'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, Clock3, FileText, UserRound } from 'lucide-react';
import { api } from '../../lib/api';
type Request = { id:string; status:string; customerName:string; customerPhone:string; description?:string|null; createdAt:string; service:{name:string}; agent?:{displayName:string;phone:string;location:string}|null };

export default function RequestsPage(){
 const [items,setItems]=useState<Request[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{const token=localStorage.getItem('lumia_token'); if(!token){setLoading(false);return;} api<{requests:Request[]}>('/api/v1/irembo/service-requests',{headers:{Authorization:'Bearer '+token}}).then(r=>setItems(r.requests)).catch(e=>setError(e instanceof Error?e.message:'Unable to load requests')).finally(()=>setLoading(false));},[]);
 return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={15}/> Dashboard</Link><div className="text-sm font-semibold">My requests</div><div className="w-20"/></div></header><div className="mx-auto max-w-5xl px-5 py-10"><div className="text-sm font-medium text-slate-500">SERVICE REQUESTS</div><h1 className="mt-2 text-4xl font-semibold tracking-tight">Track your requests.</h1><p className="mt-3 text-slate-600">See the current state of services you asked LUMIA or an agent to help with.</p>{loading&&<div className="mt-8 text-sm text-slate-500">Loading…</div>}{error&&<div className="mt-8 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-8 space-y-3">{items.map(r=><div key={r.id} className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div className="flex items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-slate-100"><FileText size={18}/></div><div><h2 className="font-semibold">{r.service.name}</h2><div className="mt-2 flex flex-wrap gap-3 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><Clock3 size={13}/>{new Date(r.createdAt).toLocaleString()}</span><span className="inline-flex items-center gap-1"><UserRound size={13}/>{r.agent?.displayName||'Not assigned'}</span></div></div></div><span className="w-fit rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold">{r.status}</span></div></div>)}</div></div></main>
}