'use client';

import Link from 'next/link';
import { useEffect,useState } from 'react';
import { useParams } from 'next/navigation';
import { api } from '../../../lib/api';

type Product={id:string;name:string;category:string;description:string|null;priceRwf:number|null;imageUrl:string|null;productUrl:string|null;sourceShop:string|null;sourceUrl:string|null;verifiedAt:string|null;stock:number;partner:{businessName:string;phone:string;location:string;description:string|null}};

export default function ProductPage(){
 const params=useParams<{id:string}>(); const [p,setP]=useState<Product|null>(null); const [qty,setQty]=useState(1); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [location,setLocation]=useState(''); const [notes,setNotes]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{void api<{product:Product}>('/api/v1/marketplace/products/'+params.id).then(d=>setP(d.product)).catch(e=>setMessage(e instanceof Error?e.message:'Product not found')).finally(()=>setLoading(false));},[params.id]);
 async function order(e:React.FormEvent){e.preventDefault();setMessage('');const token=localStorage.getItem('lumia_token');if(!token){setMessage('Banza winjire muri LUMIA kugirango ukore order.');return;}try{const r=await api<{orderId:string}>('/api/v1/marketplace/orders',{method:'POST',headers:{Authorization:'Bearer '+token},body:JSON.stringify({productId:p?.id,quantity:qty,customerName:name,customerPhone:phone,deliveryLocation:location,notes:notes||undefined})});setMessage('Order yakiriwe. Order ID: '+r.orderId);}catch(e){setMessage(e instanceof Error?e.message:'Order failed.');}}
 if(loading)return <main className="min-h-screen grid place-items-center">Loading...</main>;
 if(!p)return <main className="min-h-screen p-8"><Link href="/marketplace">← Marketplace</Link><p className="mt-8">{message}</p></main>;
 return <main className="min-h-screen bg-slate-50 text-slate-950"><div className="mx-auto max-w-5xl px-5 py-8"><Link href="/marketplace" className="text-sm text-slate-500">← Marketplace</Link><div className="mt-6 grid gap-8 lg:grid-cols-2"><div className="aspect-square overflow-hidden rounded-3xl bg-white border border-slate-200">{p.imageUrl?<img src={p.imageUrl} alt={p.name} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-slate-400">No image</div>}</div><div><div className="text-xs uppercase tracking-wider text-slate-400">{p.category}</div><h1 className="mt-2 text-3xl font-semibold">{p.name}</h1><div className="mt-3 text-2xl font-semibold">{p.priceRwf==null?'Price on request':p.priceRwf.toLocaleString()+' RWF'}</div><p className="mt-4 whitespace-pre-wrap text-slate-600">{p.description||'No description provided.'}</p><div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4"><div className="font-semibold">{p.partner.businessName}</div><div className="mt-1 text-sm text-slate-500">{p.partner.location} · {p.partner.phone}</div>{p.sourceShop&&<div className="mt-3 text-sm font-semibold text-emerald-700">Original source: {p.sourceShop}</div>}{p.sourceUrl&&<a href={p.sourceUrl} target="_blank" rel="noreferrer" className="mt-1 inline-block text-xs text-slate-500">View source shop</a>}{p.verifiedAt&&<div className="mt-1 text-xs text-slate-400">Price verified: {new Date(p.verifiedAt).toLocaleDateString()}</div>}</div><form onSubmit={order} className="mt-6 space-y-3 rounded-3xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Place order</h2><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" className="w-full rounded-xl border p-3"/><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+250..." className="w-full rounded-xl border p-3"/><input required value={location} onChange={e=>setLocation(e.target.value)} placeholder="Delivery location" className="w-full rounded-xl border p-3"/><input required type="number" min="1" max={p.stock} value={qty} onChange={e=>setQty(Number(e.target.value))} className="w-full rounded-xl border p-3"/><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notes (optional)" className="w-full rounded-xl border p-3"/><button className="w-full rounded-xl bg-slate-950 p-3 font-semibold text-white">Submit order</button>{p.productUrl&&<a href={p.productUrl} target="_blank" rel="noreferrer" className="block text-center text-sm text-violet-600">Open seller product link</a>}{message&&<div className="rounded-xl bg-slate-50 p-3 text-sm">{message}</div>}</form></div></div></div></main>;
}
